# ─── Cloudflare Worker (comments API) ───
# Deploy with: npx wrangler deploy -c wrangler-api.toml
name = "pacme-api"
main = "worker/index.js"
compatibility_date = "2024-01-01"
account_id = "24db3a948e66b99b8dc77345f5745ea0"

kv_namespaces = [
  { binding = "COMMENTS", id = "e1b21522fff14c5283b9a235356683c8" }
]

[vars]
API_SECRET = "pacme-dev-2026-x7k9m"
